version: '3.4'

services:
  catalogodb:
    container_name: catalogodb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogoDb 
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalogo:/var/lib/postgresql/data/
  catalogo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogodb;Port=5432;Database=CatalogoDb;User Id=postgres;Password=postgres;Include Error Detail=true 
    depends_on:
      - catalogodb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
